name: blackduck scan
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Black Duck Full Scan
        if: ${{ github.event_name != 'pull_request' }}
        uses: synopsys-sig/synopsys-action@v1.6.0
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
          DETECT_PROJECT_VERSION_NAME: STAGE
          DETECT_ACCURACY_REQUIRED: NONE
        with:
          blackduck_url: ${{ secrets.BLACKDUCK_URL }}
          blackduck_token: ${{ secrets.BLACKDUCK_TOKEN }}
          blackduck_scan_full: true
          blackduck_scan_failure_severities: 'BLOCKER,CRITICAL'
 
          ### Uncomment below configuration to enable automatic fix pull request creation if vulnerabilities are reported
          # blackduck_fixpr_enabled: true
          # blackduck_fixpr_maxCount: 5
          # blackduck_fixpr_filter_severities: 'CRITICAL,HIGH'
          # blackduck_fixpr_useUpgradeGuidance: 'SHORT_TERM,LONG_TERM'
          # github_token: ${{ secrets.GITHUB_TOKEN }} # Mandatory when blackduck_fixpr_enabled is set to 'true'
  
          ### Uncomment below configuration if Synopsys Bridge diagnostic files needs to be uploaded
          # include_diagnostics: true
       # - name: Black Duck PR Scan
       #   if: ${{ github.event_name == 'pull_request' }}
       #   uses: synopsys-sig/synopsys-action@v1.6.0
  
       #   ### Use below configuration to set specific detect environment variables
       #   env:
       #     DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
       #   with:
       #     blackduck_url: ${{ secrets.BLACKDUCK_URL }}
       #     blackduck_token: ${{ secrets.BLACKDUCK_TOKEN }}
       #     blackduck_scan_full: false
  
       #     ### Below configuration is used to enable automatic pull request comment based on Black Duck scan result
       #     blackduck_prComment_enabled: true
       #     github_token: ${{ secrets.GITHUB_TOKEN }} 
           # Mandatory when blackduck_automation_prcomment is set to 'true'
 
           ### Uncomment below configuration if Synopsys Bridge diagnostic files needs to be uploaded
           # include_diagnostics: true

# name: Detect iNTELLIGENT Scan Action
# on:
#   push:
#     branches: [ main, master, develop, stage, release ]
#   pull_request:
#     branches: [ main, master, develop, stage, release ]
# jobs:
#   build:
#     runs-on: [ ubuntu-latest ]
#     steps:
#       - name: Checkout Source
#         uses: actions/checkout@v3
#       - name: Black Duck Full Scan
#         if: ${{ github.event_name != 'pull_request' }}
#         # uses: synopsys-sig/synopsys-action@v1.6.0
#         uses: synopsys-sig/detect-action@v0.3.4
#         env:
#           DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
#           DETECT_ACCURACY_REQUIRED: ALL
#           DETECT_RISK_REPORT_PDF: TRUE
#           # DETECT_RISK_REPORT_PDF_PATH: /.
#         with:
#           detect-version: 9.3.0
#           blackduck-url: https://blackduck.apps.carrier.com
#           blackduck-api-token: MDYzM2FmZjQtNzI0MS00N2MxLTk4ZTYtMDE4NDE3ODMyYmY4OjM3MjVjZDBiLTdiZmItNDljYy05Y2M1LWYyMGQ0ZjIwM2U0ZA==
#           # fail-on-all-policy-severities: 'BLOCKER,CRITICAL'
